version: '2'
services:
  jhipstersampleapplication8-app:
    image: jhipstersampleapplication8
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication8-mysql:3306/jhipstersampleapplication8?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
  jhipstersampleapplication8-mysql:
    extends:
      file: mysql.yml
      service: jhipstersampleapplication8-mysql
